server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: catalogRoute
          uri: lb://catalog-service:8082
          predicates:
          - Path=/catalog/**
        - id: movieRoute
          uri: lb://movie-service:8081
          predicates:
          - Path=/movie/**
